const { contextBridge, ipcRenderer } = require('electron');
const send = (ch) => (...a) => ipcRenderer.send(ch, ...a);
const on = (ch) => (cb) => ipcRenderer.on(ch, (_e, ...a) => cb(...a));

contextBridge.exposeInMainWorld('api', {
  navigate: send('navigate'), back: send('back'), forward: send('forward'), reload: send('reload'), home: send('home'), focusPage: send('focus-page'),
  tabNew: send('tab-new'), tabActivate: send('tab-activate'), tabClose: send('tab-close'), tabContext: send('tab-context'),
  tabNewPrivate: send('tab-new-private'), tabSetSession: (o) => ipcRenderer.send('tab-set-session', o), newtabMenu: send('newtab-menu'),
  groupRename: send('group-rename'), groupToggle: send('group-toggle'), groupClose: send('group-close'),
  tabMove: send('tab-move'), groupMove: send('group-move'),
  tabClosePair: send('tab-close-pair'), tabMovePair: send('tab-move-pair'),
  setTheme: send('set-theme'),
  setDevMode: send('set-dev-mode'), devOpen: send('dev-open'),
  browsingDataStats: () => ipcRenderer.invoke('browsing-data-stats'),
  clearBrowsingData: (opts) => ipcRenderer.invoke('clear-browsing-data', opts),
  historyList: () => ipcRenderer.invoke('history-list'),
  historyRemove: (key) => ipcRenderer.invoke('history-remove', key),
  permsList: () => ipcRenderer.invoke('perms-list'),
  permsRemove: (key) => ipcRenderer.invoke('perms-remove', key),
  cookiesList: () => ipcRenderer.invoke('cookies-list'),
  cookiesRemove: (domain) => ipcRenderer.invoke('cookies-remove', domain),
  cacheSize: () => ipcRenderer.invoke('cache-size'),
  cacheClear: () => ipcRenderer.invoke('cache-clear'),
  settingsGet: () => ipcRenderer.invoke('settings-get'),
  settingsSet: (patch) => ipcRenderer.invoke('settings-set', patch),
  pickDownloadDir: () => ipcRenderer.invoke('pick-download-dir'),
  zoomList: () => ipcRenderer.invoke('zoom-list'),
  zoomReset: (host) => ipcRenderer.invoke('zoom-reset', host),
  zoomResetAll: () => ipcRenderer.invoke('zoom-reset-all'),
  setSearchEngine: send('set-search-engine'),
  favToggle: send('fav-toggle'), favAdd: send('fav-add'), favFolder: send('fav-folder'), favRemove: send('fav-remove'),
  favRename: send('fav-rename'), favToggleFolder: send('fav-toggle-folder'),
  favCustomize: (o) => ipcRenderer.send('fav-customize', o),
  onCustomizeFav: on('customize-fav'),
  favOpen: send('fav-open'), favOpenNew: send('fav-open-new'), favOpenAll: send('fav-open-all'),
  favMove: send('fav-move'), favContext: send('fav-context'),
  onRenameFav: on('rename-fav'),
  appActivate: send('app-activate'), appContext: send('app-context'), appAdd: send('app-add'),
  appPeek: (id, clientY) => ipcRenderer.send('app-peek', { id, clientY }), appPeekHideSoon: send('app-peek-hide-soon'),
  sidebarToggle: send('sidebar-toggle'), overlay: send('overlay'),
  splitOpen: send('split-open'), splitClose: send('split-close'), splitMenu: send('split-menu'),
  splitBack: send('split-back'), splitForward: send('split-forward'), splitReload: send('split-reload'), splitNavigate: send('split-navigate'),
  splitResizeStart: send('split-resize-start'), splitResize: send('split-resize'), splitResizeEnd: send('split-resize-end'),
  sidebarResizeStart: send('sidebar-resize-start'), sidebarResize: send('sidebar-resize'), sidebarResizeEnd: send('sidebar-resize-end'),
  search: (q) => ipcRenderer.invoke('search', q),
  archiveList: () => ipcRenderer.invoke('archive-list'),
  archiveRestore: send('archive-restore'), archiveRemove: send('archive-remove'),
  openUrl: send('open-url'), openUrlNew: send('open-url-new'),
  pwAvailable: () => ipcRenderer.invoke('pw-available'),
  pwImport: () => ipcRenderer.invoke('pw-import'),
  pwList: () => ipcRenderer.invoke('pw-list'),
  pwReveal: (id) => ipcRenderer.invoke('pw-reveal', id),
  pwCopy: send('pw-copy'), pwOpen: send('pw-open'), pwDelete: send('pw-delete'), pwClear: send('pw-clear'),
  onState: on('state'), onFocusUrl: on('focus-url'), onOpenPalette: on('open-palette'), onRenameGroup: on('rename-group'),
  onGmailCount: on('gmail-count'),
  onExportMd: on('export-md'), mdCopy: send('md-copy'), mdDownload: (o) => ipcRenderer.invoke('md-download', o),
  tipShow: send('tip-show'), tipHide: send('tip-hide'),
  findOpen: send('find-open-req'), findQuery: send('find-query'), findClose: send('find-close'),
  omniSuggest: (q) => ipcRenderer.invoke('omni-suggest', q),
  omniGoogle: (q) => ipcRenderer.invoke('omni-google', q),
  suggestShow: send('suggest-show'), suggestHide: send('suggest-hide'),
  onSuggestHover: on('suggest-hover'), onSuggestChoose: on('suggest-choose'),
  claudeToggle: send('claude-toggle'),
  claudeRun: (prompt) => ipcRenderer.invoke('claude-run', prompt),
  claudeTasks: () => ipcRenderer.invoke('claude-tasks'),
  claudeCancel: send('claude-cancel'), claudeRemove: send('claude-remove'), claudeClearDone: send('claude-clear-done'),
  claudeContinue: (o) => ipcRenderer.send('claude-continue', o),
  claudeOpenMd: send('claude-open-md'),
  claudeOpenLink: (o) => ipcRenderer.send('claude-open-link', o),
  claudeOpenIsland: send('claude-open-island'), claudeFocusIsland: send('claude-focus-island'),
  claudeRevealTask: send('claude-reveal-task'),
  onClaudeTasks: on('claude-tasks'), onClaudeReveal: on('claude-reveal'),
  dlList: () => ipcRenderer.invoke('dl-list'),
  dlOpen: send('dl-open'), dlFolder: send('dl-folder'), dlCancel: send('dl-cancel'), dlRemove: send('dl-remove'), dlClear: send('dl-clear'),
  onDownloads: on('downloads'), onDownloadStarted: on('download-started'),
});
